### ISSUE TITLE
INFOGRAFIA SISTEMAS NUMERICOS 

### ISSUE THREAD

**Issue by QUET012** [SistemasTecTlaxiaco/infografia-QUET012#2]
[24620200_Quetzalli Garcia Garcia_1as.pdf](https://github.com/user-attachments/files/16754132/24620200_Quetzalli.Garcia.Garcia_1as.pdf)

**Comment by W1ll1am21** [comment]
Redacción y Ortografía:13/14
Exposición de ideas Centrales:16/16
Organización de ideas centrales:14/14
Uso de Imágenes y Colores:14/14
Presentación Visual:14/14
Referencias:13/14
Presentación:14/14
Calificación Final: 19.6

**Comment by josealfredo79** [comment]
bien hecho y revisado..
